spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:librarydb
    username: lorena
    password: lorena
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  doc:
    swagger-ui:
      path: /swagger-ui.html
  security:
    user:
      name: lorena
      password: lorena
server:
  forward-headers-strategy: framework
  port: 1337
jwt_secret: lorena e smechera