spring:
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.Oracle10gDialect
  datasource:
    url: jdbc:h2:mem:librarydb
    username: lorena
    password: lorena
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  doc:
    swagger-ui:
      path: /swagger-ui.html
server:
  forward-headers-strategy: framework

